name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: pnpm install --frozen-lockfile
      - name: Changesets Action
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bundle exec rake release:publish
          version: bundle exec rake release:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Output of Changesets Action
        run: |
          echo "Published versions: ${{ steps.changesets.outputs.publishedVersions }}"
          echo "Published: ${{ steps.changesets.outputs.published }}"
